added add external evaluator api
nerubia/kh360-nodejs pull request #141
Opened 2023-11-21 01:01 UTC by jatnerubia

Ticket ID: [Create API to add external evaluators to Evaluation Administration](https://github.com/orgs/nerubia/projects/18/views/2?pane=issue&itemId=44534085)

2023-11-21 03:38 UTC, emmaacha approved these changes

2023-11-22 01:18 UTC, emmaacha requested changes
I think this should be changed pala so that multiple evaluators can be added

2023-11-22 02:56 UTC, Dev-Nino approved these changes

2023-11-22 05:46 UTC, emmaacha approved these changes

2023-11-22 05:46 UTC, merged