add bod route for evaluation results page
nerubia/kh360-nodejs pull request #351
Opened 2023-12-20 06:59 UTC by emmaacha

Ticket ID: [Evaluation Results - add new menu item for Evaluation Results#351](https://github.com/nerubia/kh360-react/issues/351#issuecomment-1863821748)

FE PR:

2023-12-20 07:30 UTC, jatnerubia requested changes
^^

2023-12-20 07:30 UTC, jatnerubia commented on src/middlewares/bod-middleware.ts
> +      if (decodedToken.roles === undefined) {
do we need this? 🤔

2023-12-20 09:02 UTC, emmaacha commented
Done ^^

2023-12-21 02:17 UTC, jatnerubia approved these changes
Nice

2023-12-21 02:17 UTC, merged