update apis for new my evaluation results screen
nerubia/kh360-nodejs pull request #353
Opened 2023-12-20 09:04 UTC by emmaacha

Ticket ID: [My Evaluaton Results - Enhancements Revision 1#368](https://github.com/nerubia/kh360-react/issues/368)

FE PR:

2023-12-21 02:18 UTC, jatnerubia approved these changes
Cool

2023-12-21 02:22 UTC, jatnerubia requested changes
^^

2023-12-21 02:22 UTC, jatnerubia commented on src/controllers/user/score-rating-controller.ts
> +import * as ScoreRatingSerice from "../../services/score-rating-service"
typo

2023-12-21 02:22 UTC, jatnerubia commented on src/routes/user/user-route.ts
> +router.get("/score-ratings", ScoreRatingController.index)
fix order

2023-12-21 02:55 UTC, emmaacha commented
Done ^^

2023-12-21 02:57 UTC, jatnerubia approved these changes
Cool

2023-12-22 06:05 UTC, gborgonia-ir approved these changes

2023-12-22 06:12 UTC, closed without merging