349 email templates api
nerubia/kh360-nodejs pull request #359
Opened 2023-12-22 01:13 UTC by gborgonia-ir

Ticket ID: #349

2023-12-27 06:57 UTC, emmaacha approved these changes

2023-12-28 06:10 UTC, jatnerubia requested changes
just a few changes ^^

2023-12-28 06:10 UTC, jatnerubia commented on src/controllers/admin/email-template-controller.ts
> +    const templateType = type === "all" ? "" : type
move all logic to service

2023-12-28 06:10 UTC, jatnerubia commented on src/controllers/admin/email-template-controller.ts
> +    const emailTemplate = await EmailTemplateService.getById(parseInt(id))
same

2023-12-28 06:10 UTC, jatnerubia commented on src/controllers/admin/email-template-controller.ts
> +    const template = await EmailTemplateService.getById(parseInt(id))
same

2023-12-28 08:58 UTC, jatnerubia approved these changes
Cool

2023-12-28 09:07 UTC, merged