update edit eval admin to not allow edit for ongoing status
nerubia/kh360-nodejs pull request #497
Opened 2024-03-05 08:55 UTC by emmaacha

Ticket ID: [Able to edit in Admin Evaluation with 'Ongoing' status #849](https://github.com/nerubia/kh360-react/issues/849)

FE PR: [update edit eval admin to not allow edit for ongoing status #851](https://github.com/nerubia/kh360-react/pull/851)

2024-03-06 02:03 UTC, gborgonia-ir requested changes
@emmaacha for eval admin with status Pending, im not able to edit Name value. For status Draft it is working as expected

<img width="948" alt="image" src="https://github.com/nerubia/kh360-nodejs/assets/62045758/8f0ae23f-830d-4ac0-87bf-b021f2fc6b2c">

2024-03-06 05:12 UTC, emmaacha commented
Done ^^

2024-03-06 06:11 UTC, gborgonia-ir approved these changes

2024-03-07 00:38 UTC, chadiegilnerubia approved these changes

2024-03-07 00:38 UTC, merged