node-515-survey-administration-crud-operations
nerubia/kh360-nodejs pull request #518
Opened 2024-03-15 04:18 UTC by chadiegilnerubia

Ticket ID:
Create API to Create / Retrieve / Update / Delete Survey Administration
[#515](https://github.com/nerubia/kh360-nodejs/issues/515)

2024-03-15 05:46 UTC, emmaacha requested changes

2024-03-15 05:46 UTC, emmaacha commented on src/controllers/admin/survey-administration-controller.ts
> +    }
Please put these inside survey-administration-service

2024-03-15 05:46 UTC, emmaacha commented on src/controllers/admin/survey-administration-controller.ts
> +      status,
I think status should not be manually updated here in this api, we can remove status here

2024-03-15 05:46 UTC, emmaacha commented on src/controllers/admin/survey-administration-controller.ts
> +      status,
We won't be passing status here so we can remove this

2024-03-15 05:46 UTC, emmaacha commented on src/controllers/admin/survey-administration-controller.ts
> +      status: status as string,
We can remove this

2024-03-18 09:33 UTC, emmaacha requested changes

2024-03-18 09:33 UTC, emmaacha commented on src/routes/admin/survey-administration.ts
Kindly rename this to `survey-administration-route.ts`

2024-03-18 09:35 UTC, emmaacha requested changes

2024-03-18 09:35 UTC, emmaacha commented on src/controllers/admin/survey-administration-controller.ts
> +
Please put this in survey administration service

2024-03-19 07:25 UTC, emmaacha approved these changes

2024-03-19 07:31 UTC, emmaacha requested changes

2024-03-19 07:31 UTC, emmaacha commented on src/controllers/admin/survey-administration-controller.ts
> +    })
Kindly add status: SurveyAdministrationStatus.Draft here to auto set the status to Draft

2024-03-19 09:05 UTC, emmaacha approved these changes

2024-03-20 00:14 UTC, gborgonia-ir approved these changes

2024-03-20 00:14 UTC, merged