node-1119-skill-map-search-api
nerubia/kh360-nodejs pull request #629
Opened 2024-06-03 05:22 UTC by chadiegilnerubia

Ticket ID:
Create and Integrate API for Skill Map Search screen
[#1119](https://github.com/nerubia/kh360-react/issues/1119)

2024-06-05 06:39 UTC, jatnerubia requested changes
minor changes ^^

2024-06-05 06:39 UTC, jatnerubia commented on src/services/skill-map-search-service.ts
> +/* eslint-disable no-console */
remove this ^^

2024-06-05 06:39 UTC, jatnerubia commented on src/services/skill-map-search-service.ts
> +  // Filter by name
remove this ^^

2024-06-05 06:39 UTC, jatnerubia commented on src/services/skill-map-search-service.ts
> +  const filteredResultsBySkill = []
remove this ^^

2024-06-05 06:39 UTC, jatnerubia commented on src/services/skill-map-search-service.ts
> +  // Implement pagination
remove this ^^

2024-06-06 04:00 UTC, chadiegilnerubia commented on src/services/skill-map-search-service.ts
> +/* eslint-disable no-console */
done :3

2024-06-06 05:37 UTC, jatnerubia approved these changes
Cool

2024-06-06 05:37 UTC, merged