update apis for perf eval screen and user eval admin list
nerubia/kh360-nodejs pull request #93
Opened 2023-11-10 06:03 UTC by emmaacha

Ticket ID: [Create API for Evaluations - Eval Admin List #83](https://github.com/nerubia/kh360-nodejs/issues/83)

FE PR: [create performance evaluation form and eval admin list #117 ](https://github.com/nerubia/kh360-react/pull/117)

2023-11-10 07:47 UTC, Dev-Nino approved these changes

2023-11-10 07:53 UTC, jatnerubia requested changes
just a few changes ^^

2023-11-10 07:53 UTC, jatnerubia commented on src/controllers/admin/evaluation_template_contents_controller.ts
>  export const index = async (req: Request, res: Response) => {
we should move this to user? 🤔

2023-11-10 07:53 UTC, jatnerubia commented on src/controllers/user/user_controller.ts
> -        for_evaluation: Boolean(parseInt(for_evaluation as string)),
we should use `0` or `1` in the request then parse it

2023-11-10 07:53 UTC, jatnerubia commented on src/controllers/user/user_controller.ts
> +    const sortedEvaluations = evaluationDetails.sort((a, b) => {
sort it on FE

2023-11-10 07:53 UTC, jatnerubia commented on src/controllers/user/user_controller.ts
> +    const allEvaluationRatings = await prisma.evaluation_ratings.findMany({
let's just check the comment in `submitEvaluation`

2023-11-13 05:24 UTC, jatnerubia requested changes
just a few changes ^^

2023-11-13 05:24 UTC, jatnerubia commented on src/routes/admin/users_route.ts
> +router.get("/all", getAllUsers)
duplicate? 🤔

2023-11-13 05:24 UTC, jatnerubia commented on src/types/userType.ts
do we still use this? 🤔

2023-11-13 06:18 UTC, emmaacha commented on src/types/userType.ts
Nice catch kuys, will remove, thanks!

2023-11-13 07:16 UTC, jatnerubia approved these changes
Nice

2023-11-13 07:16 UTC, merged